name: my_pos
description: My Pos Plugin
version: 0.1.0
homepage: https://github.com/mhmmdlkts/flutter_my_pos_plugin

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.kreiseck.my_pos
        pluginClass: MyPosPlugin
